name: GitHub Actions
run-name: ${{ github.actor }} is testing project files using Coveralls 🚀
on: ["push", "pull_request"]
jobs:
  Test-Coveralls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: npm install
        run: |
          npm install

      - name: npm run coverage
        run: |
          npm run coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v2
